# Generated by Django 5.2.5 on 2025-08-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='business_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiops.businessservice'),
        ),
    ]
