# Generated by Django 5.2.5 on 2025-08-30 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0002_workitem_business_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiops.asset'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiops.vendor'),
        ),
    ]
