# Generated by Django 5.2.5 on 2025-08-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0003_workitem_asset_workitem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
