# Generated by Django 5.2.5 on 2025-08-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0004_workitem_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskregister',
            old_name='service',
            new_name='business_service',
        ),
    ]
