# Generated by Django 5.2.5 on 2025-08-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0005_rename_service_riskregister_business_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationexecutionlog',
            name='message',
            field=models.CharField(default='Automation ran fine', max_length=500),
            preserve_default=False,
        ),
    ]
